### ISSUE TITLE
识别的时候使用cpu 2秒多使用显卡4秒多

### ISSUE THREAD

**Issue by guanzhao** [PaddlePaddle/PaddleClas#1445]
1.   PaddlePaddle2.2  PaddleClas的版本是2.3
 2. 训练环境信息：
  a. Linux Ubuntu20.04 
  b. Python3.8
  c. CUDA 11.2/cuDNN 8.1.1
  d. 硬件 cpu: 铜牌 3204 显卡 :P1000
 3. cls 配置文件 
```
Global:
  infer_imgs: null
  inference_model_dir: null
  batch_size: 1
  use_gpu: True
  enable_mkldnn: False
  cpu_num_threads: 10
  enable_benchmark: False
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False
PreProcess:
  transform_ops:
    - ResizeImage:
        resize_short: 256
    - CropImage:
        size: 224
    - NormalizeImage:
        scale: 0.00392157
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
        channel_num: 3
    - ToCHWImage:
PostProcess:
  main_indicator: Topk
  Topk:
    topk: 5
    class_id_map_file: null 
```

配置中null的部分通过程序已做处理.

4. 问题描述： 训练使用 显卡一切正常, 识别的时候使用显卡4秒 使用CPU 2秒多， 所有的训练图集都是处理过的最大不超过200kb 普遍都是 40-80kb , 识别的图像也经过处理 50kb 左右
