### ISSUE TITLE
[BUG] 2.3 版本 不支持配置文件加入 lr_mult_list: [0.5, 0.5, 0.6, 0.6, 0.8]

### ISSUE THREAD

**Issue by xixixihaha** [PaddlePaddle/PaddleClas#1879]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：

### 必要信息
** 如果您不能提供以下必要信息，可能会影响问题解决的速度 **
#### 1. PaddleClas版本以及PaddlePaddle版本
2.3
#### 2. 最小可复现问题的方法
修改 ResNet50_vd.yaml
name: ResNet50_vd
后加入
params:
        lr_mult_list: [0.5, 0.5, 0.6, 0.6, 0.8]

#### 3. 报错信息和log
提示
TypeError: __init__() got an unexpected keyword argument 'params'

去掉param这两行信息，运行正常

**Comment by TingquanGao** [comment]
这样试试呢：

```yaml
# model architecture
Arch:
  name: ResNet50_vd
  class_num: 1000
  lr_mult_list: [0.5, 0.5, 0.6, 0.6, 0.8]
```
