### ISSUE TITLE
c++版本推理开启mkldnn加速报错could not execute a primitive

### ISSUE THREAD

**Issue by onair1314** [PaddlePaddle/PaddleClas#2024]
使用环境：
paddlepaddle 2.3.0
paddleClas 2.4.0

采用c++版本推理，采用的模型为ResNet50导出的inference model，配置文件inference_cls.yaml中默认enable_mkldnn: True，即默认开启mkldnn加速
单进程依次对一万张图片进行图片分类，每次运行若干张图片后（每次报错时的图片均不相同）均会报错：
terminate called after throwing an instance of 'dnnl::error'
  what():  could not execute a primitive
通过查看源码，认为该报错来源为：https://oneapi-src.github.io/oneDNN/v2/getting_started_cpp.html

同时查看paddle的issue，有同样的报错：https://github.com/PaddlePaddle/Paddle/issues/34492

因此尝试设置enable_mkldnn: False，测试发现不再有报错
因此认为该报错是由于mkldnn引起，但无法确定是由于paddleClas的代码导致还是由于paddle代码未修复成功导致，亦或由于paddle的mkldnn加速不支持ResNet50导致
恳请各位大神协助解决

**Comment by HydrogenSulfate** [comment]
你好，目前正在跟进复现这个问题，有进展会在本issue回复

**Comment by HydrogenSulfate** [comment]
你好，目前用paddlepaddle 2.3.0.post101，paddleClas 2.4.0的组合暂时没有复现出这个问题，预测输出中没有任何报错，我的yaml文件如下
```yaml
Global:
  infer_imgs: "/workspace/PaddleClas/deploy/images/1w"
  inference_model_dir: "/workspace/PaddleClas/inference"
  batch_size: 1
  use_gpu: False
  enable_mkldnn: True
  cpu_num_threads: 1
  enable_benchmark: False
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

PreProcess:
  transform_ops:
    - ResizeImage:
        resize_short: 256
    - CropImage:
        size: 224
    - NormalizeImage:
        scale: 0.00392157
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
        channel_num: 3
    - ToCHWImage:

PostProcess:
  main_indicator: Topk
  Topk:
    topk: 5
    class_id_map_file: "../ppcls/utils/imagenet1k_label_list.txt"
  SavePreLabel:
    save_dir: ./pre_label/
```
图片是1张图像复制了10000次放到了1w这个文件夹下
