### ISSUE TITLE
Build New Teacher/Student yml

### ISSUE THREAD

**Issue by jaideep11061982** [PaddlePaddle/PaddleClas#2272]
@ZeyuChen @QingshuChen @procr @jacquesqiao @zhxfl 
Can we introduce new pair of Teacher/student models apart from what is provided in /configs/Imagenet/Distillition

**Comment by littletomatodonkey** [comment]
The Student/Teacher model arch is same as that of single model. You can assign it as any model you want.

```yaml
  models:                      # 子网络列表
    - Teacher:                 # 教师模型
        name: ResNet50_vd      # 模型名称
        class_num: *class_num  # 类别数
        pretrained: True       # 预训练模型路径，如果为True，则会从官网下载默认的预训练模型
        use_ssld: True         # 是否使用SSLD蒸馏得到的预训练模型，精度会更高一些
    - Student:                 # 学生模型
        name: PPLCNet_x2_5     # 模型名称
        class_num: *class_num  # 类别数
        pretrained: False      # 预训练模型路径，可以指定为bool值或者字符串，这里为False，表示学生模型默认不加载预训练模型
```

For more methods' tutorial, you can refer to: https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.5/docs/zh_CN/advanced_tutorials/knowledge_distillation.md
