### ISSUE TITLE
static 分支使用官方提供的 yaml 文件训练 GoogleNet, 不收敛。

### ISSUE THREAD

**Issue by taosean** [PaddlePaddle/PaddleClas#2445]
1. PaddleClas版本: release/static
2. 训练环境：
  a. OS: Ubuntu18.04
  b. GPU: A10
  c. python, cuda 以及 paddlepaddle 版本信息：使用以下 docker
    `nvidia-docker pull registry.baidubce.com/paddlepaddle/paddle:2.3.2-gpu-cuda11.2-cudnn8`
3. 训练脚本
``` bash
python -m paddle.distributed.launch \
    --gpus="0" \
    tools/train.py \
        -c ./configs/Inception/GoogLeNet.yaml \
        -o print_interval=10 \
        --vdl_dir=vdl_logs/googlenet_v9_imagenet1k
```
5. 配置文件 GoogLeNet.yaml
```yaml

valid_interval: 1
epochs: 120
topk: 5
image_shape: [3, 224, 224]

LEARNING_RATE:
   function: 'Cosine'
   params:
       lr: 0.01

OPTIMIZER:
    function: 'Momentum'
    params:
        momentum: 0.9
    regularizer:
        function: 'L2'
        factor: 0.0001

TRAIN:
    batch_size: 256
    num_workers: 4
    file_list: "./dataset/imagenet_raw/train_list.txt"
    data_dir: "./dataset/imagenet_raw/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - RandCropImage:
            size: 224
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1./255.
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:

VALID:
    batch_size: 64
    num_workers: 4
    file_list: "./dataset/imagenet_raw/evaluate/val.txt"
    data_dir: "./dataset/imagenet_raw/evaluate/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - ResizeImage:
            resize_short: 256
        - CropImage:
            size: 224
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:
```

我尝试使用了 flower102, imagenet50, imagenet1k 这三个数据集，在 train from scratch 的情况下，都无法收敛。
请问这是什么问题？
