### ISSUE TITLE
【咨询】关于所有配置文件【数据transform】中的Infer都比Train多一个ToCHWImage，这是什么原因呢？

### ISSUE THREAD

**Issue by wenmingwei** [PaddlePaddle/PaddleClas#2548]
Train中的
```yaml
Train:
    dataset:
      name: ImageNetDataset
      image_root: ./dataset/ILSVRC2012/
      cls_label_path: ./dataset/ILSVRC2012/train_list.txt
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - RandCropImage:
            size: 224
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1.0
            mean: [123.675, 116.28, 103.53]
            std: [58.395, 57.12, 57.375]
            order: ''
```
Infer的配置
```yaml
Infer:
  infer_imgs: docs/images/inference_deployment/whl_demo.jpg
  batch_size: 10
  transforms:
    - DecodeImage:
        to_rgb: True
        channel_first: False
    - ResizeImage:
        resize_short: 256
    - CropImage:
        size: 224
    - NormalizeImage:
        scale: 1.0
        mean: [123.675, 116.28, 103.53]
        std: [58.395, 57.12, 57.375]
        order: ''
    - ToCHWImage:
  PostProcess:
    name: Topk
    topk: 5
    class_id_map_file: ppcls/utils/imagenet1k_label_list.txt
```

后续自行实现inference时，做请求数据的预处理时，是否需要`ToCHWImage`。
