### ISSUE TITLE
REID Center Loss Learning Rate

### ISSUE THREAD

**Issue by awarebayes** [PaddlePaddle/PaddleClas#2887]
In file `ppcls/configs/reid/strong_baseline/softmax_triplet_with_center.yaml`
 ```yml
Optimizer:
  - Adam:
      scope: RecModel
      lr:
        name: Piecewise
        decay_epochs: [30, 60]
        values: [0.00035, 0.000035, 0.0000035]
        warmup_epoch: 10
        warmup_start_lr: 0.0000035
        by_epoch: True
        last_epoch: 0
      regularizer:
        name: "L2"
        coeff: 0.0005
  - SGD:
      scope: CenterLoss
      lr:
        name: Constant
        learning_rate: 1000 # NOTE: set to ori_lr*(1/centerloss_weight) to avoid manually scaling centers' gradidents.
```
Number 1000 seems to big to be used as a learning rate for sgd. I think it needs to be changed.
It is not clear what ori_lr refers to... Is it 0.0000035 in adam?
