### ISSUE TITLE
优化器多个scope 作用域的问题

### ISSUE THREAD

**Issue by hsuanguo** [PaddlePaddle/PaddleClas#2929]
比如以下的[例子](https://github.com/PaddlePaddle/PaddleClas/blob/develop/ppcls/configs/reid/MetaBIN_ResNet50_cross_domain.yaml)(改自)

```
Optimizer:
  - SGD:
      scope: "backbone"
      lr:
        name: Constant
        learning_rate: 0.2
        last_epoch: -1
  - SGD:
      scope: "RecModel"
      lr:
        name: Cyclic
        epochs: *epochs
        step_each_epoch: *iter_per_epoch
        base_learning_rate: 0.001
        max_learning_rate: 0.1
        warmup_epoch: 0
        warmup_start_lr: 1
        step_size_up: 1095
        step_size_down: 1095
        by_epoch: False
        last_epoch: 0
```

RecModel 包含了backbone, neck 和head， 那么两个optimizer 会同时作用于"backbone"？ 还是其中有优先级的概念？
感谢！

@HydrogenSulfate
