### ISSUE TITLE
ML Decoder 的两个小问题

### ISSUE THREAD

**Issue by thsno02** [PaddlePaddle/PaddleClas#2977]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：develop
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

https://github.com/PaddlePaddle/PaddleClas/blob/2200f30052634249ec6c985c711184e8fbff5a74/ppcls/arch/gears/__init__.py#L43

无法读取到 model.class_num，目前的 workaround 是，在 MLDecoder 中添加 `class_num`，可解决。

文档中 https://github.com/PaddlePaddle/PaddleClas/blob/develop/ppcls/configs/MultiLabelCOCO/MLDecoder/README.md 的配置信息不对：

```
# model architecture
Arch:
  name: ResNet101
  class_num: 80
  pretrained: True
  # use ml-decoder head to replace avg_pool and fc
  use_ml_decoder: True

# ml-decoder head
MLDecoder:
  query_num: 80 # default: 80, query_num <= class_num
  in_chans: 2048
```

in_chans 应为 in_channels

**Comment by lzm-build** [comment]
@thsno02 你好
1. 出现第一个问题的原因是ppcls中的某些backbone网络无法直接获取class_num导致的，直接再yml中的MLDecoder中添加class_num并注释掉这一句代码就可以。
2. 是换变量名后，readme这里漏了
总之，多谢了。

**Comment by kennyvoo** [comment]
@MINGtoMING 还有一个小问题就是readme 的 eval command 错了。
应该是
```bash
python3 tools/eval.py \
    -c ./ppcls/configs/MultiLabelCOCO/MLDecoder/ResNet101_ml_decoder_448.yaml \
    -o Global.pretrained_model="./output/ResNet101_ml_decoder_448/best_model"
```
instead of 
```bash
python3 tools/eval.py \
    -c ./ppcls/configs/MultiLabelCOCO/MLDecoder/ResNet101_ml_decoder_448.yaml \
    -o Arch.pretrained"./output/ResNet101_ml_decoder_448/best_model"
```

**Comment by lzm-build** [comment]
@kennyvoo 好的多谢，我已更正在最新提交的 [pr](https://github.com/PaddlePaddle/PaddleClas/pull/2991)  .

**Comment by kennyvoo** [comment]
@MINGtoMING 
想请教一下。
如果是用efficientnet, 我需要remove 这个conv  吗？ 还是只需要remove fc?
用这个是能够run 的， 但不懂对不对。
```yaml
  remove_layers: []
  replace_layer: '_fc'
```

```bash
   ...
  (_conv): ConvBNLayer(
    (_conv): Conv2ds(
      (_conv): Conv2D(384, 1536, kernel_size=[1, 1], padding=[0, 0], data_format=NCHW)
    )
    (_bn): BatchNorm()
  )
  (_pool): AdaptiveAvgPool2D(output_size=1)
  (_drop): Dropout(p=0.3, axis=None, mode=upscale_in_train)
  (_fc): Linear(in_features=1536, out_features=6, dtype=float32)
```

**Comment by lzm-build** [comment]
@kennyvoo 

以`EfficientNetB0`为例， 对应的MLDecoder配置示例：
```yaml

# model architecture
Arch:
  name: EfficientNetB0
  class_num: 80
  pretrained: True
  # use ml-decoder head to replace avg_pool and fc
  use_ml_decoder: True

# ml-decoder head
MLDecoder:
  query_num: 80 # default: 80, query_num <= class_num
  in_channels: 1280
  class_num: 80
  remove_layers: [ '_pool', '_drop']
  replace_layer: '_fc'

```

改成这样就可以正常跑了， 不过去掉了drop层，可以考虑调一下MLDecoder的`dropout`参数。
