### ISSUE TITLE
关于EfficientNetB4的configs配置

### ISSUE THREAD

**Issue by yhhu99** [PaddlePaddle/PaddleClas#321]
在configs/EfficientNet文件夹目录下没有EfficientNetB4.yaml，而用EfficientNetB0的配置文件测试得到的准确率和官方提供的不太一样，所以想问下EfficientNetB4的配置应该是怎么样的呢？

**Comment by littletomatodonkey** [comment]
你好想问下你是怎么测试的呢?
```
```

**Comment by yhhu99** [comment]
> 你好想问下你是怎么测试的呢? 我用下面这种方式预测，指标没有问题呀
> 
> ```
> python3.7 -m paddle.distributed.launch \
>     --selected_gpus="0" \
>     tools/eval.py \
>         -c configs/EfficientNet/EfficientNetB0.yaml \
>         -o pretrained_model=./pretrained/EfficientNetB0_pretrained/
> ```

你好，感谢回答！EfficientNetB0的确没有问题，但是我是想要测EfficientnetB4的指标，所以想问下有没有EfficientNetB4的配置文件。

**Comment by littletomatodonkey** [comment]
你好，目前没有提供EfficientNetB4的训练配置，不过你可以加载我们的预训练模型，配置文件中VALID部分参数如下所示，与B0的区别就是`resize_short=412`和`CropImage.size=380`。其他EfficientNet的一些评估的超参，也可以从这里查看：[link](https://github.com/PaddlePaddle/PaddleClas/blob/master/docs/en/models/EfficientNet_and_ResNeXt101_wsl_en.md#inference-speed-based-on-v100-gpu)

```
VALID:
    batch_size: 64
    num_workers: 4
    file_list: "./dataset/ILSVRC2012/val_list.txt"
    data_dir: "./dataset/ILSVRC2012/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - ResizeImage:
            interpolation: 2
            resize_short: 412
        - CropImage:
            size: 380
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:
```
