### ISSUE TITLE
dataloader无法正确加载数据

### ISSUE THREAD

**Issue by wwma** [PaddlePaddle/PaddleClas#3236]
使用PPLCNetV2_base对自己的数据集进行微调，配置文件如下：
```
# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output/classification2
  device: gpu
  save_interval: 1
  eval_during_train: True
  eval_interval: 1
  epochs: 480
  print_batch_step: 10
  use_visualdl: False
  # used for static mode and model export
  image_shape: [3, 512, 512]
  save_inference_dir: ./inference/classification2


# mixed precision
AMP:
  use_amp: False
  use_fp16_test: False
  scale_loss: 128.0
  use_dynamic_loss_scaling: True
  use_promote: False
  # O1: mixed fp16, O2: pure fp16
  level: O1


# model architecture
Arch:
  name: PPLCNetV2_base
  class_num: 2
  pretrained: True

# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
        epsilon: 0.1
  Eval:
    - CELoss:
        weight: 1.0

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Cosine
    learning_rate: 0.08
    warmup_epoch: 5
  regularizer:
    name: 'L2'
    coeff: 0.00004

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: ImageNetDataset
      image_root: dataset/road/
      cls_label_path: dataset/road/train.txt
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - RandCropImage:
            size: 512
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''

    # support to specify width and height respectively:
    # scales: [(160,160), (192,192), (224,224) (288,288) (320,320)]
    sampler:
      name: MultiScaleSampler
      scales: [160, 192, 224, 288, 320]
      # first_bs: batch size for the first image resolution in the scales list
      # divide_factor: to ensure the width and height dimensions can be devided by downsampling multiple
      first_bs: 500
      divided_factor: 32
      is_training: True
    loader:
      num_workers: 4
      use_shared_memory: True

  Eval:
    dataset: 
      name: ImageNetDataset
      image_root: dataset/road/
      cls_label_path: dataset/road/val.txt
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - ResizeImage:
            resize_short: 512
        - CropImage:
            size: 512
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
    sampler:
      name: DistributedBatchSampler
      batch_size: 64
      drop_last: False
      shuffle: False
    loader:
      num_workers: 4
      use_shared_memory: True

Infer:
  infer_imgs: docs/images/inference_deployment/whl_demo.jpg
  batch_size: 10
  transforms:
    - DecodeImage:
        to_rgb: True
        channel_first: False
    - ResizeImage:
        resize_short: 512
    - CropImage:
        size: 512
    - NormalizeImage:
        scale: 1.0/255.0
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ''
    - ToCHWImage:
  PostProcess:
    name: Topk
    topk: 5
    class_id_map_file: ppcls/utils/imagenet1k_label_list.txt

Metric:
  Train:
    - TopkAcc:
        topk: [1, 5]
  Eval:
    - TopkAcc:
        topk: [1, 5]
```
在dataloader中提示错误，错误信息如下：
```
Traceback (most recent call last):
  File "C:\Users\DELL\.conda\envs\paddle\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\DELL\.conda\envs\paddle\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\DELL\.conda\envs\paddle\lib\site-packages\paddle\io\dataloader\dataloader_iter.py", line 235, in _thread_loop 
   batch = self._dataset_fetcher.fetch(
  File "C:\Users\DELL\.conda\envs\paddle\lib\site-packages\paddle\io\dataloader\fetcher.py", line 77, in fetch
    print(self.dataset[idx])
  File "C:\Users\DELL\Desktop\PaddleClas\ppcls\data\dataloader\common_dataset.py", line 81, in __getitem__
    format(self.images[idx], ex))
TypeError: list indices must be integers or slices, not tuple
```
debug发现，self.images为一个列表，保存着训练集图片的路径，而idx为一个元组，内容为（288，288，54）。不知道这个id为什么会呈现这样？
