### ISSUE TITLE
C++部署问题

### ISSUE THREAD

**Issue by OpenCDR** [PaddlePaddle/PaddleClas#3242]
1. PaddleClas 2.5.2&paddlepaddle-gpu 2.6
 2. 训练环境信息：
  a. Linux
  b. Python3.8
  c. CUDA11.6/cuDNN 8.4

在使用[quick_start/](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5.2/docs/zh_CN/quick_start/quick_start_classification_professional.md)这个方法对模型进行训练后并导出模型，使用devlop/cpp下的程序进行部署，模型的推理结果不正常，第41类的置信度始终最高：
![image](https://github.com/user-attachments/assets/842305c2-da71-4f02-b178-f412dd6ad497)
请问出现了什么问题？
我的inference.yaml附在下面：
```yaml
Global:
  infer_imgs: "./CIFAR100/train/1"
  inference_model_dir: "./infer_model"
  batch_size: 1
  use_gpu: True
  enable_mkldnn: True
  cpu_num_threads: 10
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

PreProcess:
  transform_ops:
    - ResizeImage:
        resize_short: 36
    - CropImage:
        size: 32
    - NormalizeImage:
        scale: 0.00392157
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
        order: ""
        channel_num: 3
    - ToCHWImage:

PostProcess:
  main_indicator: Topk
  Topk:
    topk: 5
    class_id_map_file: "./infer_model/label_list.txt"
  SavePreLabel:
    save_dir: ./pre_label/

```
paddle_inference的版本为：
```txt
Paddle version: 2.5.2
GIT COMMIT ID: 3a1b1659a405a044ce806fbe027cc146f1193e6d
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
WITH_ROCM: OFF
WITH_IPU: OFF
CUDA version: 11.2
CUDNN version: v8.2
CXX compiler version: 8.2.0
WITH_TENSORRT: ON
TensorRT version: v8.0.3.4
```
