### ISSUE TITLE
PaddleX 3.0，训练多标签模型（CLIP_vit_base_patch16_448_ML），显存泄露

### ISSUE THREAD

**Issue by 188080501** [PaddlePaddle/PaddleClas#3289]
显存泄露问题，甚至是每个epoch都会导致显存增长，而且我已经关闭了eval，只训练

我的环境是
PaddleX 3.0-beta1
Windows10 ltsc 2019
Python 3.10
CUDA 11.8
4090显卡

PaddleClas是通过插件安装的，命令如下：
paddlex --install PaddleClas

训练命令：
python main.py -c paddlex/configs/multilabel_classification/CLIP_vit_base_patch16_448_ML.yaml -o Global.mode=train -o Global.dataset_dir=./dataset/mlcls_nus_examples -o Global.device=gpu:0

PaddleX的代码无修改，ymal只修改了训练的配置，修改后的配置如下：
```
Train:
  num_classes: 33
  epochs_iters: 20
  batch_size: 16
  learning_rate: 0.0003
  pretrain_weight_path: null
  warmup_steps: 5
  resume_path: null
  log_interval: 20
  eval_interval: 20
  save_interval: 4
```

MSI Afterburner的截图
![捕获](https://github.com/user-attachments/assets/e7aa7690-b8e9-456a-80e9-37d1ff42e782)
