### ISSUE TITLE
训练自定义数据集出错

### ISSUE THREAD

**Issue by choimroc** [PaddlePaddle/PaddleClas#588]
在代码里面找到了`ResizeImage : size`解决了resize的问题(建议补充config文档)，但是又遇到新的问题
```
RuntimeError: (NotFound) Operator conv2d does not have kernel for data_type[uint8_t]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[CUDNN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at D:\v2.0.0\paddle\paddle\fluid\imperative\prepared_operator.cc:127)
  [operator < conv2d > error]
```

我的环境是：
Windows 10
CUDA 10.2
CUDNN 7.6.5
paddlepaddle-gpu 2.0

- - -

你好，我在训练自定义数据集时一直报错` DataLoader reader thread raised an exception`；我检查了自己的配置文件，查看了源码，都看不出来问题在哪里。我的图片数据是放在`F:/DRD/train`，机器的内存和显存也是正常的。

这是配置
```yaml
TRAIN:
  batch_size: 32
  num_workers: 0
  file_list: "./custom/train_list.txt"
  data_dir: "F:/DRD/train"
  shuffle_seed: 0
  transforms:
    - DecodeImage:
        to_rgb: False
        to_np: False
        channel_first: False
    - NormalizeImage:
        scale: 1./255.
```

这是`train_list.txt`的数据格式
```
10_left.jpeg 0
10_right.jpeg 0
13_left.jpeg 0
13_right.jpeg 0
15_left.jpeg 1
15_right.jpeg 2
16_left.jpeg 4
16_right.jpeg 4
```

补充：通过debug后解决了一开始遇到的问题，现在遇到了新的问题`all input arrays must have the same shape`，我的数据里面所有图片的尺寸不是固定的，但是框架在数据预处理的时候没有根据设定的`image_shape`进行resize吗？是需要自己来进行resize吗？
